import { useMemo } from "react";
import { Bot, Brain, Clock, TrendingUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { useAgents, useAutomationRules, useFollowUps, useLeads } from "@/lib/lead-manager/queries";
import { leadApi } from "@/lib/lead-manager/api";
import type { Lead } from "@/lib/lead-manager/types";
import { LeadTable } from "../LeadTable";
import { Panel, StatCard, num, relTime } from "../shared";
import { leadNameMap, useAction } from "./common";

const DAY = 24 * 60 * 60 * 1000;

export function AutomationScreen({ onSelect }: { onSelect: (lead: Lead) => void }) {
  const { data: leads = [], isLoading } = useLeads();
  const { data: agents = [] } = useAgents();
  const { data: rules = [] } = useAutomationRules();
  const { data: followUps = [] } = useFollowUps();
  const run = useAction();

  const dropOff = useMemo(
    () =>
      leads.filter(
        (l) =>
          !["won", "lost", "spam"].includes(l.status) &&
          Date.now() - new Date(l.last_contact_at ?? l.created_at).getTime() > 5 * DAY,
      ),
    [leads],
  );
  const highProbability = useMemo(
    () => [...leads].sort((a, b) => Number(b.conversion_probability) - Number(a.conversion_probability)).slice(0, 10),
    [leads],
  );

  const bestTime = useMemo(() => {
    const buckets = new Map<string, number>();
    for (const l of leads) {
      const hour = new Date(l.created_at).getHours();
      const band = hour < 12 ? "09:00 – 12:00" : hour < 16 ? "12:00 – 16:00" : hour < 19 ? "16:00 – 19:00" : "19:00 – 22:00";
      buckets.set(band, (buckets.get(band) ?? 0) + 1);
    }
    return [...buckets.entries()].sort((a, b) => b[1] - a[1]);
  }, [leads]);

  const leadNames = leadNameMap(leads);

  return (
    <div className="space-y-6">
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Active automations" value={num(rules.filter((r) => r.is_active).length)} icon={Bot} />
        <StatCard label="Suggested follow-ups" value={num(followUps.filter((f) => !f.is_completed).length)} icon={Clock} tone="info" />
        <StatCard label="Drop-off risk" value={num(dropOff.length)} tone="destructive" />
        <StatCard label="Avg conversion probability" value={`${leads.length ? Math.round(leads.reduce((a, l) => a + Number(l.conversion_probability), 0) / leads.length) : 0}%`} icon={TrendingUp} tone="success" />
      </div>

      <Panel title="Automation & AI rules" description="Each rule runs server-side against the live lead database.">
        <div className="grid gap-3 md:grid-cols-2">
          {rules.map((r) => (
            <div key={r.id} className="flex items-start justify-between gap-3 rounded-md border border-border bg-surface-2 p-3">
              <div>
                <p className="text-sm font-medium">{r.name}</p>
                <p className="text-xs text-muted-foreground">{r.description}</p>
                <p className="mt-1 text-xs text-muted-foreground">
                  Trigger: {r.trigger_event.replace(/_/g, " ")} • accuracy {Number(r.accuracy)}% • {num(r.execution_count)} runs
                  {r.last_executed_at ? ` • last ${relTime(r.last_executed_at)}` : ""}
                </p>
              </div>
              <Switch
                checked={r.is_active}
                onCheckedChange={(v) => run(() => leadApi.toggleAutomationRule(r.rule_key, v), `${r.name} ${v ? "enabled" : "paused"}`)}
              />
            </div>
          ))}
        </div>
      </Panel>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel title="Best time to call" description="Derived from when leads actually arrive and respond.">
          <div className="space-y-2">
            {bestTime.map(([band, count]) => (
              <div key={band} className="flex items-center justify-between rounded-md border border-border bg-surface-2 px-3 py-2 text-sm">
                <span>{band}</span>
                <Badge variant="outline">{count} leads</Badge>
              </div>
            ))}
          </div>
        </Panel>

        <Panel title="Auto follow-up suggestions" description="Scheduled next touchpoints generated by the automation engine.">
          <div className="space-y-2">
            {followUps.filter((f) => !f.is_completed).slice(0, 8).map((f) => (
              <div key={f.id} className="rounded-md border border-border bg-surface-2 p-3">
                <div className="flex items-center justify-between text-sm">
                  <span className="font-medium">{leadNames.get(f.lead_id) ?? "Lead"}</span>
                  <Badge variant="outline">{f.follow_up_type}</Badge>
                </div>
                <p className="text-xs text-muted-foreground">
                  {relTime(f.scheduled_at)} • {f.suggested_message ?? f.notes ?? "No script attached"}
                </p>
                <Button
                  size="sm"
                  variant="ghost"
                  className="mt-1 h-7 px-2 text-xs"
                  onClick={() => run(() => leadApi.completeFollowUp(f.id, "Completed from automation board"), "Follow-up completed")}
                >
                  Mark complete
                </Button>
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <Panel
        title={`Drop-off alerts — ${dropOff.length} leads going cold`}
        description="No contact recorded in over five days. Re-score to refresh their probability, or reach out immediately."
        actions={
          <Button
            size="sm"
            variant="secondary"
            disabled={dropOff.length === 0}
            onClick={() =>
              run(async () => {
                for (const l of dropOff.slice(0, 10)) await leadApi.rescoreLead(l.id);
              }, "Cold leads re-scored")
            }
          >
            <Brain className="size-4" /> Re-score cold leads
          </Button>
        }
      >
        <LeadTable
          leads={dropOff}
          agents={agents}
          isLoading={isLoading}
          onSelect={onSelect}
          emptyTitle="No leads are going cold"
          columns={["source", "status", "agent", "score", "value", "created"]}
        />
      </Panel>

      <Panel title="Highest conversion probability" description="Where the model expects the next wins to come from.">
        <LeadTable
          leads={highProbability}
          agents={agents}
          onSelect={onSelect}
          columns={["source", "status", "agent", "score", "intent", "value"]}
        />
      </Panel>
    </div>
  );
}
